### ISSUE TITLE
Can't host judgehost successful in docker

### ISSUE THREAD

**Issue by waterbeta** [DOMjudge/domjudge#1977]
**Description of the problem**
I use docker with .yml to host a domjudge, but it just host sucessful without any judgehost.

**Your environment**
- Docker version 20.10.21
- Linux HP 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Domjudge 8.2.0

**Steps to reproduce**
I referred the following url: https://hackmd.io/@johnson10024/H1zzm2Lo5

1. install docker and composer
2. edit dj.yml
```
version: '3'

services:
        dj-mariadb:
                image: mariadb
                volumes:
                        - /home/beta/djbackup:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=rootpw
                        - MYSQL_DATABASE=domjudge
                        - MYSQL_USER=domjudge
                        - MYSQL_PASSWORD=djpw
                ports:
                        - 13306:3306
                command:
                        --max-connections=1000

        dj-domserver:
                image: domjudge/domserver:latest
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                environment:
                        - CONTAINER_TIMEZONE=Asia/Taipei
                        - MYSQL_HOST=mariadb
                        - MYSQL_ROOT_PASSWORD=rootpw
                        - MYSQL_DATABASE=domjudge
                        - MYSQL_USER=domjudge
                        - MYSQL_PASSWORD=djpw
                ports:
                        - 9487:80
                links:
                        - dj-mariadb:mariadb
        dj-judgehost:
                image: domjudge/judgehost:latest
                privileged: true
                hostname: judgedaemon-0
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                environment:
                        - CONTAINER_TIMEZONE=Asia/Taipei
                        - JUDGEDAEMON_PASSWORD=pw
                        - DAEMON_ID=0
                        #- DOMSERVER_BASEURL=127.0.0.1
                links:
                        - dj-domserver:domserver

        dj-judgehost_2:
                image: domjudge/judgehost:latest
                privileged: true
                hostname: judgedaemon-1
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                environment:
                        - CONTAINER_TIMEZONE=Asia/Taipei
                        - JUDGEDAEMON_PASSWORD=pw
                        - DAEMON_ID=1
                links:
                        - dj-domserver:domserver

        dj-judgehost_3:
                image: domjudge/judgehost:latest
                privileged: true
                hostname: judgedaemon-2
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                environment:
                        - CONTAINER_TIMEZONE=Asia/Taipei
                        - JUDGEDAEMON_PASSWORD=pw
                        - DAEMON_ID=2
                links:
                        - dj-domserver:domserver

        dj-judgehost_4:
                image: domjudge/judgehost:latest
                privileged: true
                hostname: judgedaemon-3
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                environment:
                        - CONTAINER_TIMEZONE=Asia/Taipei
                        - JUDGEDAEMON_PASSWORD=pw
                        - DAEMON_ID=3
                links:
                        - dj-domserver:domserver
```
3. sudo docker-compose -f dj.yml up -d 
  and i found that there's only host mariadb and domserver because cgroup issue
4. fixed cgroup issue by edit /etc/default/grub to below: 
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0 isolcpus=2"` and reboot
5. sudo docker-compose -f dj.yml up -d again <<Another Error and I stop here.

**Expected behaviour**
I can see all host can be up-to-date like: 
```
docker-dj_dj-mariadb_1 is up-to-date
docker-dj_dj-domserver_1 is up-to-date
docker-dj_dj-judgehost_2_1 is up-to-date
docker-dj_dj-judgehost_4_1 is up-to-date
docker-dj_dj-judgehost_3_1 is up-to-date
docker-dj_dj-judgehost_1 is up-to-date
```

**Actual behaviour**
It can just host in 5 seconds and exit error.
I used `sudo docker-compose -f dj.yml up` to found logs
I found  error messages: 
```
dj-judgehost_1    | [ok] Container timezone set to: Asia/Taipei
dj-judgehost_1    |
dj-judgehost_1    | [..] Setting up restapi file
dj-judgehost_1    | [ok] Restapi file set up
dj-judgehost_1    |
dj-judgehost_1    | [..] Setting up cgroups
dj-judgehost_1    | [ok] cgroups set up
dj-judgehost_1    |
dj-judgehost_1    | [..] Copying resolv.conf to chroot
dj-judgehost_1    | [ok] resolv.conf copied
dj-judgehost_1    |
dj-judgehost_1    | [Apr 04 23:15:10.193] judgedaemon[36]: Judge started on judgedaemon-0-0 [DOMjudge/8.2.0]
dj-judgehost_1    | [Apr 04 23:15:10.197] judgedaemon[36]: 🔏 Executing chroot script: 'chroot-startstop.sh check'
dj-judgehost_1    | [Apr 04 23:15:10.267] judgedaemon[36]: Registering judgehost on endpoint default: http://domserver/api/v4
dj-judgehost_1    | [Apr 04 23:15:10.288] judgedaemon[36]: warning: Authentication failed (error 401) while contacting http://domserver/api/v4/judgehosts. Check credentials in restapi.secret.
dj-judgehost_1    | [Apr 04 23:15:10.288] judgedaemon[36]: Registering judgehost on endpoint default failed.
dj-judgehost_1    | [Apr 04 23:15:10.326] judgedaemon[36]: error: Authentication failed (error 401) while contacting http://domserver/api/v4/config?. Check credentials in restapi.secret.
docker-dj_dj-judgehost_1 exited with code 1
```
Every judgehosts show same error messages.

I search some issues and it seems restapi.secret need to be edit.
But I can understand where should I edit this file, and what should I modify / add to it.

Or maybe domjudge hosted by docker with .yml need somethings else to fix it?

**other information**
I'm not use English as mother language.
So if there's some grammar mistakes, I'm very sorry about that.
