### ISSUE TITLE
Unwanted redirect from HTTP to HTTPS on login

### ISSUE THREAD

**Issue by goldmont** [DOMjudge/domjudge#2177]
### Description of the problem
> I'm running DOMjudge in a Docker container behind a reverse proxy. The login page is reachable at [http://domjudge.lab.edu/login](http://domjudge.lab.school/login) but, as soon as I submit the login form, I'm redirected to [https://domjudge.lab.edu/login](https://domjudge.lab.school/login) (HTTPS). I'm not planning to setup a secure environment since there is no "sensitive" data moving around in the network so I would like not opening the 443 port just to make the login work. I don't think there is a mistake in my configuration. However, I would love having your help to solve this issue. Thank you.

### Your environment
> Include details about your installation here.
> - DOMjudge version: domjudge/domserver:8.2.1

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Visit DOMjudge login page
> - Enter credentials
> - Submit

### Expected behaviour
> Being able to login without switching to HTTPS.

### Actual behaviour
> Login fails because the protocol get switched to HTTPS and the port 443 is closed on my server.

**Comment by nickygerritsen** [comment]
Could you try using the direct Docker endpoint to access the app and log in? I haven't seen this before and want to make sure what part is the issue.

**Comment by goldmont** [comment]
> Could you try using the direct Docker endpoint to access the app and log in? I haven't seen this before and want to make sure what part is the issue.

Hi,

By removing the reverse proxy and thus using the server IP address directly, the problem disappears. By the way, I have other services, behind the reverse proxy, that requires authentication. So, I don't understand where the problem is. Could it be the browser fault?

**Comment by vmcj** [comment]
Can you post the headers you receive from the proxy?

**Comment by goldmont** [comment]
> Can you post the headers you receive from the proxy?

Hi, sure.

In my network tab, I have two entries named "login":

First entry:
![image](https://github.com/DOMjudge/domjudge/assets/6855692/ca7a2f5a-6647-4648-ab10-c52c64af8e07)

Second entry (It failed because the reverse proxy isn't configured for HTTPS e thus there is no entrypoint):
![image](https://github.com/DOMjudge/domjudge/assets/6855692/7cd329e0-f94f-463d-a411-ab436a6b554d)

**Comment by nickygerritsen** [comment]
I suspect the proxy is sending something we didn't expect.
Could you play with this block: https://github.com/nickygerritsen/domjudge/blob/main/etc/nginx-conf-inner.in#L43-L56
inside the docker image? The block might be there twice. I would for example try commenting out the `fastcgi_param HTTPS` line.

It is installed in `/etc/nginx/snippets` I believe. After changing it, run `supervisorctl restart nginx` in Docker to apply the changes.

**Comment by goldmont** [comment]
> I suspect the proxy is sending something we didn't expect. Could you play with this block: https://github.com/nickygerritsen/domjudge/blob/main/etc/nginx-conf-inner.in#L43-L56 inside the docker image? The block might be there twice. I would for example try commenting out the `fastcgi_param HTTPS` line.
> 
> It is installed in `/etc/nginx/snippets` I believe. After changing it, run `supervisorctl restart nginx` in Docker to apply the changes.

Hi,

I've edited the file `/etc/nginx/fastcgi.conf` by commenting out `fastcgi_param  HTTPS  $https if_not_empty;` line and then I've applied the changes but no luck. It still redirects me to HTTPS. I've also tried to restart the Docker container.

**Comment by nickygerritsen** [comment]
Hmmm is there any way you could tell us more about your reverse proxy, how it is set up etc? I think without it I'm at a bit of a loss.

**Comment by goldmont** [comment]
> Hmmm is there any way you could tell us more about your reverse proxy, how it is set up etc? I think without it I'm at a bit of a loss.

Hi,

I'm using Traefik v2.10.1 as reverse proxy with basic configuration. I've not configured any redirect or anything else. I don't understand why DOMjudge switches to HTTPS protocol. How can I make DOMjudge run only on HTTP protocol? Maybe there is a rule that needs to be set. Thanks, enjoy your weekend.

**Comment by vmcj** [comment]
> > Hmmm is there any way you could tell us more about your reverse proxy, how it is set up etc? I think without it I'm at a bit of a loss.
> 
> Hi,
> 
> I'm using Traefik v2.10.1 as reverse proxy with basic configuration. I've not configured any redirect or anything else. I don't understand why DOMjudge switches to HTTPS protocol. How can I make DOMjudge run only on HTTP protocol? Maybe there is a rule that needs to be set. Thanks, enjoy your weekend.

Can you post your traffic config so we can try to reproduce this? Can you check if HSTS is maybe set (https://security.stackexchange.com/a/92957).

**Comment by goldmont** [comment]
> > > Hmmm is there any way you could tell us more about your reverse proxy, how it is set up etc? I think without it I'm at a bit of a loss.
> > 
> > 
> > Hi,
> > I'm using Traefik v2.10.1 as reverse proxy with basic configuration. I've not configured any redirect or anything else. I don't understand why DOMjudge switches to HTTPS protocol. How can I make DOMjudge run only on HTTP protocol? Maybe there is a rule that needs to be set. Thanks, enjoy your weekend.
> 
> Can you post your traffic config so we can try to reproduce this? Can you check if HSTS is maybe set (https://security.stackexchange.com/a/92957).

Hi, sure.

Traefik:
```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[api]
  dashboard = true
  insecure = false

[log]
  level = "DEBUG"

[accessLog]
  bufferingSize = 100

[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers]
  providersThrottleDuration = 2
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    network = "proxy_network"
    watch = true
  [providers.file]
    directory = "/config/files"
    watch = true
```

DOMjudge:
```yaml
version: "3.8"

services:
  domjudge:
    container_name: domjudge
    image: domjudge/domserver:8.2.1
    restart: unless-stopped
    privileged: true
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - WEBAPP_BASEURL=/
      - CONTAINER_TIMEZONE=Europe/Rome
    networks:
      - mariadb_network
      - proxy_network
    labels:
      - traefik.enable=true
      - traefik.http.services.domjudge.loadbalancer.server.port=80
      - traefik.http.routers.domjudge.rule=Host(`domjudge.lab.school`)

networks:
  mariadb_network:
    external: true
  proxy_network:
    external: true
```

By the way, I saw [these](https://github.com/DOMjudge/domjudge/blob/355e1d5a74593f08b41bc7f2abbca1a8cd846026/etc/nginx-conf.in#L13-L18) lines which are suspicious.
