### ISSUE TITLE
Add a way to distinguish solves in the freeze on the jury scoreboard

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#2572]
Either always or with some flag show submissions that are accepted in the freeze differently on the jury scoreboard, so that you know what 'the action' will be.

**Comment by meisterT** [comment]
What about something like this?

![glow](https://github.com/DOMjudge/domjudge/assets/418721/793a2f79-ab67-417d-acae-ae9e2c76c5bf)

**Comment by nickygerritsen** [comment]
👀 fancyyyy. Would using a glow that has the same blue color as pending be ugly?

We also need to add it to the legend of course.

**Comment by meisterT** [comment]
I like the current effect more than the blue I tried, but I created a PR so you can play around with it yourself, perhaps you find a better color.

**Comment by nickygerritsen** [comment]
Thanks, will try it on a screen that has better colors than the TV I am currently using

**Comment by mpsijm** [comment]
I feel like the orange glowy effect is not very visible against the green cells, but I have a slight green-deficiency so I'm not sure if it's just me :stuck_out_tongue: 

Maybe a suggestion: would it help to also (slightly) change the tint of the green background? :slightly_smiling_face:

**Comment by nickygerritsen** [comment]
It seems like you like to do frontend stuff 😛. Want to give it a try?

**Comment by meisterT** [comment]
Is this too much?
![glow_bg](https://github.com/DOMjudge/domjudge/assets/418721/c0a2a7c2-4d57-4858-98bf-36b06557b4d4)

**Comment by mpsijm** [comment]
@nickygerritsen Sorry, didn't find the time last week :see_no_evil: 

@meisterT That is a bit intense :joy: Especially when the jury has the scoreboard open on some external screen for monitoring...

But, this did give me another idea. Does it have to be an animation? We could also do something with multi-coloured cells, which may be easier on the eyes:
![image](https://github.com/DOMjudge/domjudge/assets/9739541/f377d211-fb0f-44da-a2da-525daf98ae6c)

<details>
<summary>This uses the following extra CSS rules:</summary>

```css
.score_correct.score_pending {
    background: linear-gradient(45deg, #60E760, #6666FF);
}

.score_correct.score_first.score_pending {
    background: linear-gradient(45deg, #1DAA1E, #6666FF) !important;
}

.score_incorrect.score_pending {
    background: linear-gradient(45deg, #E87272, #6666FF);
}
```

By the way, `!important` would probably not be needed if the already existing `.score_first` rule would be selected using `.score_correct..score_first`, because that selector is more specific :slightly_smiling_face: 

</details>

The `45deg` of the `linear-gradient` has been arbitrarily chosen by Chrome DevTools' tab completion :joy: I'm also fine with any other multiple of 45 degrees, whatever people like best :slightly_smiling_face: 

Additionally, we could use the "x+y tries" sub-text for these partly-pending-partly-resolved submissions. This makes the jury scoreboard look even closer to the public scoreboard :smile:
