### ISSUE TITLE
Move configuration settings out of migrations

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge#664]
As discussed in #661 it is not very nice to have the configuration settings spread across multiple migrations. It would be way better to have a central place to manage them.

My suggestion would be to create a file `etc/db-configuration.yaml` that contains something like

```yaml
- category: Scoring
  configuration:
  - name: verification_required
    type: bool
    value: false
    public: false
    description: Is verification of judgings by jury required before publication?
  # ...
  - name: results_prio
    type: array_keyval
    value:
      memory-limit: 99
      output-limit: 99
      run-error: 99
      timelimit: 99
      wrong-answer: 99
      no-output: 99
      correct: 1
    public: false
    description: Priorities of results for determining final result with multiple testcases. Higher priority is used first as final result. With equal priority, the first occurring result determines the final result.
# ...
- category: Clarification
  configuration:
  # ...
  - name: clar_answers
    type: array_val
    value:
    - No comment, read the problem statement carefully.
    - This will be addressed during the practice session results.
    public: false
    description: List of predefined clarification answers
# ...
```

Then we create a console command `domjudge:load-database-configuration` that will read that file and insert any configuration options that are missing. That command can also validate whether the YAML is actually in the correct format and the value corresponds to the type.

Extra idea: if you pass the flag `--overwrite` it will overwrite existing configuration options with the new default values as well. We can also add an option `--overwrite=x` to only set/overwrite the given config option.

This would mean we have one file to manage all configuration options and we can easily only set new config options, not overwriting other ones

Thoughts on this approach?
